// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
import { defineDeskmate } from "@deskmate/core";
import team from "../../../deskmate.config.js";

export default defineDeskmate(team, "product_analyst");
