// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
import type { Roster } from "@deskmate/core";

export const DESKMATES: Roster = {
  product_analyst: {"id":"product_analyst","displayName":"Product Analyst","emoji":":bar_chart:","summary":"Turns product usage data into a short narrative: what changed, why, what to look at next.","providers":["mixpanel"]},
  devops: {"id":"devops","displayName":"DevOps Engineer","emoji":":wrench:","summary":"Triages errors and incidents from logs/monitoring, explains likely causes, and proposes (never auto-applies) fixes.","providers":["sentry"]},
};
