// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
import { createSlackAmbientChannel } from "@deskmate/core/channels/slack-ambient";
import { DESKMATES } from "../lib/deskmates.js";

export default createSlackAmbientChannel(DESKMATES);
