// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
import { createSlackChannel } from "@deskmate/core/channels/slack";
import { DESKMATES } from "../lib/deskmates.js";

export default createSlackChannel(DESKMATES);
