// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
import { createSlackAmbientChannel } from "@deskmate/core/channels/slack-ambient";
import { DESKMATES } from "../lib/deskmates.js";
import { CHANNEL_ROUTES } from "../lib/channel-routes.js";

export default createSlackAmbientChannel(DESKMATES, CHANNEL_ROUTES);
