// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
export { default } from "../../../../roles/devops/tools/get_incident_summary.js";
export * from "../../../../roles/devops/tools/get_incident_summary.js";
