// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
export { default } from "../../../../roles/devops/tools/record_decision.js";
export * from "../../../../roles/devops/tools/record_decision.js";
