// AUTO-GENERATED by scripts/deskmate.ts — do not edit by hand.
// Roster of active deskmates. Change it with `pnpm deskmate:add|remove <id>`.
//
// Identity per deskmate, used when answering in Slack. This is also the seam that
// later becomes per-tenant / per-org config in the hosted layer.

export type DeskmateIdentity = {
  id: string;
  displayName: string;
  emoji: string;
  summary: string;
  providers: string[];
};

export const DESKMATES = {
  devops: {"id":"devops","displayName":"DevOps Engineer","emoji":":wrench:","summary":"Triages errors and incidents from logs/monitoring, explains likely causes, and proposes (never auto-applies) fixes.","providers":["sentry"]},
  product_analyst: {"id":"product_analyst","displayName":"Product Analyst","emoji":":bar_chart:","summary":"Turns product usage data into a short narrative: what changed, why, what to look at next.","providers":["mixpanel"]},
} as const satisfies Record<string, DeskmateIdentity>;

export type DeskmateId = keyof typeof DESKMATES;
