// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
export { default } from "../../../../roles/devops/connections/sentry.js";
export * from "../../../../roles/devops/connections/sentry.js";
