export type McpAuthScheme = "bearer" | "basic" | "custom-header";

export type McpTemplateOptions = {
  name: string;
  urlEnv: string;
  tokenEnv: string;
  description: string;
  tools: string[];
  scheme?: McpAuthScheme;     // default "bearer"
  headerName?: string;        // used when scheme === "custom-header"
};

/** Pure: render the TypeScript source for a read-only, env-token MCP connection. */
export function renderMcpConnection(opts: McpTemplateOptions): string {
  const allow = opts.tools.map((t) => JSON.stringify(t)).join(", ");
  const url = `process.env[${JSON.stringify(opts.urlEnv)}] || "https://example.invalid/mcp"`;
  const tokenExpr = `process.env[${JSON.stringify(opts.tokenEnv)}] || ""`;
  const scheme = opts.scheme ?? "bearer";

  // Each scheme reuses the same <PREFIX>_MCP_URL + <PREFIX>_MCP_TOKEN pair; only the
  // way the token becomes a header differs, so the config entry, .env.example, and
  // stub renderer stay identical across schemes.
  let credLine: string;
  let hint: string;
  if (scheme === "basic") {
    // Token env holds plaintext "publicKey:secretKey"; base64-encode it at runtime.
    credLine = `  headers: { Authorization: \`Basic \${Buffer.from(${tokenExpr}).toString("base64")}\` },`;
    hint = `// Set ${opts.tokenEnv} to plaintext "publicKey:secretKey" (this file base64-encodes it).`;
  } else if (scheme === "custom-header") {
    const header = opts.headerName ?? "X-Api-Key";
    credLine = `  headers: { ${JSON.stringify(header)}: ${tokenExpr} },`;
    hint = `// Set ${opts.tokenEnv} to the ${header} value.`;
  } else {
    credLine = `  auth: { getToken: async () => ({ token: ${tokenExpr} }) },`;
    hint = `// Set ${opts.urlEnv} + ${opts.tokenEnv} to run against a real server, then redeploy.`;
  }

  return `import { defineMcpClientConnection } from "eve/connections";

// Generated by \`deskmate mcp-add\`. Read-only, env-token (single-deployment).
${hint}
export default defineMcpClientConnection({
  url: ${url},
  description: ${JSON.stringify(opts.description)},
${credLine}
  tools: { allow: [${allow}] },
});
`;
}

export type ConnectTemplateOptions = {
  name: string;
  connector: string; // Vercel Connect connector UID, e.g. "vercel/deskmate"
  url: string; // the MCP runtime endpoint, e.g. "https://mcp.vercel.com"
  description: string;
  tools: string[];
};

/** Pure: render an app-scoped Vercel Connect (OAuth) MCP connection. */
export function renderConnectConnection(opts: ConnectTemplateOptions): string {
  const allow = opts.tools.map((t) => JSON.stringify(t)).join(", ");
  return `import { connect } from "@vercel/connect/eve";
import { defineMcpClientConnection } from "eve/connections";

// Generated by \`deskmate mcp-add\` (oauth). App-scoped Vercel Connect: the deskmate
// acts as itself (non-interactive). Provision the connector with \`deskmate connect ${opts.name}\`.
export default defineMcpClientConnection({
  url: ${JSON.stringify(opts.url)},
  description: ${JSON.stringify(opts.description)},
  auth: connect({ connector: ${JSON.stringify(opts.connector)}, principalType: "app" }),
  tools: { allow: [${allow}] },
});
`;
}
