export type McpTemplateOptions = {
  name: string;
  urlEnv: string;
  tokenEnv: string;
  description: string;
  tools: string[];
};

/** Pure: render the TypeScript source for a read-only, env-token MCP connection. */
export function renderMcpConnection(opts: McpTemplateOptions): string {
  const allow = opts.tools.map((t) => JSON.stringify(t)).join(", ");
  return `import { defineMcpClientConnection } from "eve/connections";

// Generated by \`pnpm deskmate:mcp:add\`. Read-only, env-token (single-deployment).
// Set ${opts.urlEnv} + ${opts.tokenEnv} to run against a real server, then redeploy.
export default defineMcpClientConnection({
  url: process.env[${JSON.stringify(opts.urlEnv)}] || "https://example.invalid/mcp",
  description: ${JSON.stringify(opts.description)},
  auth: { getToken: async () => ({ token: process.env[${JSON.stringify(opts.tokenEnv)}] || "" }) },
  tools: { allow: [${allow}] },
});
`;
}

export type ConnectTemplateOptions = {
  name: string;
  connector: string; // Vercel Connect connector UID, e.g. "vercel/deskmate"
  url: string; // the MCP runtime endpoint, e.g. "https://mcp.vercel.com"
  description: string;
  tools: string[];
};

/** Pure: render an app-scoped Vercel Connect (OAuth) MCP connection. */
export function renderConnectConnection(opts: ConnectTemplateOptions): string {
  const allow = opts.tools.map((t) => JSON.stringify(t)).join(", ");
  return `import { connect } from "@vercel/connect/eve";
import { defineMcpClientConnection } from "eve/connections";

// Generated by \`deskmate mcp-add\` (oauth). App-scoped Vercel Connect: the deskmate
// acts as itself (non-interactive). Provision the connector with \`deskmate connect ${opts.name}\`.
export default defineMcpClientConnection({
  url: ${JSON.stringify(opts.url)},
  description: ${JSON.stringify(opts.description)},
  auth: connect({ connector: ${JSON.stringify(opts.connector)}, principalType: "app" }),
  tools: { allow: [${allow}] },
});
`;
}
