// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
export { default } from "../../../../roles/product_analyst/tools/get_metric_snapshot.js";
export * from "../../../../roles/product_analyst/tools/get_metric_snapshot.js";
