import { describe, it, expect } from "vitest";
import type { TeamConfig } from "@deskmate/core";
import {
  BANNER,
  renderRootAgent,
  renderRosterRegistry,
  renderChannelRoutes,
  renderSubagentAgent,
  renderReexport,
  renderSlackChannel,
  renderSlackAmbientChannel,
  renderDeskmateSaysTool,
  renderFrontDeskInstructions,
  renderSubagentInstructions,
  renderEnvExample,
  renderStubConnection,
  renderDeskmateSweepSchedule,
} from "../src/sync/render.js";

// A minimal, hand-built TeamConfig fixture (two deskmates, two mcp connections).
// We build it as a plain object cast to TeamConfig so the renderers stay unit
// testable without importing/parsing a real config file.
const fixtureTeam = {
  model: "anthropic/claude-opus-4.6",
  frontDesk: { maxTurns: 4 },
  connections: {
    sentry: { kind: "mcp", env: "SENTRY" },
    mixpanel: { kind: "mcp", env: "MIXPANEL" },
    ledger: { kind: "tool", from: "./ledger.js" },
  },
  deskmates: {
    devops: {
      role: "devops",
      emoji: ":wrench:",
      displayName: "DevOps Engineer",
      summary: "Triages incidents.",
      reads: ["sentry"],
    },
    product_analyst: {
      role: "product_analyst",
      emoji: ":bar_chart:",
      displayName: "Product Analyst",
      summary: "Turns usage data into a narrative.",
      reads: ["mixpanel"],
    },
  },
  channels: {},
} as unknown as TeamConfig;

describe("BANNER", () => {
  it("names the command and the source of truth", () => {
    expect(BANNER).toContain("GENERATED by");
    expect(BANNER).toContain("deskmate sync");
    expect(BANNER).toContain("deskmate.config.ts");
  });
});

describe("renderRootAgent", () => {
  it("emits a defineAgent with the team model + the banner", () => {
    const out = renderRootAgent(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import { defineAgent } from "eve";');
    expect(out).toContain('model: "anthropic/claude-opus-4.6"');
    expect(out).toContain("export default defineAgent(");
  });

  it("keeps @deskmate/core external so channels don't bundle it", () => {
    const out = renderRootAgent(fixtureTeam);
    expect(out).toContain('build: { externalDependencies: ["@deskmate/core"] }');
  });
});

describe("renderSubagentAgent", () => {
  it("wires defineDeskmate(team, id) with the core + config imports", () => {
    const out = renderSubagentAgent("devops");
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import { defineDeskmate } from "@deskmate/core";');
    expect(out).toContain('import team from "../../../deskmate.config.js";');
    expect(out).toContain('export default defineDeskmate(team, "devops");');
  });
});

describe("renderRosterRegistry", () => {
  it("emits a DESKMATES Roster const with one entry per deskmate", () => {
    const out = renderRosterRegistry(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import type { Roster } from "@deskmate/core";');
    expect(out).toContain("export const DESKMATES: Roster = {");
    expect(out).toContain("devops:");
    expect(out).toContain("product_analyst:");
    expect(out).toContain('"displayName":"DevOps Engineer"');
    expect(out).toContain('"emoji":":bar_chart:"');
  });

  it("sets providers to the deskmate's reads", () => {
    const out = renderRosterRegistry(fixtureTeam);
    expect(out).toContain('"providers":["sentry"]');
    expect(out).toContain('"providers":["mixpanel"]');
  });
});

describe("renderReexport", () => {
  it("re-exports the default from the given specifier", () => {
    const out = renderReexport("../../../../roles/devops/tools/x.js");
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('export { default } from "../../../../roles/devops/tools/x.js";');
    expect(out).not.toContain("export *");
  });

  it("also re-exports named bindings when star is set", () => {
    const out = renderReexport("../x.js", { star: true });
    expect(out).toContain('export { default } from "../x.js";');
    expect(out).toContain('export * from "../x.js";');
  });
});

describe("channel + tool shims", () => {
  it("slack channel shim calls createSlackChannel with the config maxTurns arg", () => {
    const out = renderSlackChannel(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import { createSlackChannel } from "@deskmate/core/channels/slack";');
    expect(out).toContain('import { DESKMATES } from "../lib/deskmates.js";');
    expect(out).toContain('import { CHANNEL_ROUTES } from "../lib/channel-routes.js";');
    expect(out).toContain("export default createSlackChannel(DESKMATES, CHANNEL_ROUTES, 4);");
  });

  it("slack-ambient shim calls createSlackAmbientChannel with the config maxTurns arg", () => {
    const out = renderSlackAmbientChannel(fixtureTeam);
    expect(out).toContain(
      'import { createSlackAmbientChannel } from "@deskmate/core/channels/slack-ambient";',
    );
    expect(out).toContain('import { CHANNEL_ROUTES } from "../lib/channel-routes.js";');
    expect(out).toContain("export default createSlackAmbientChannel(DESKMATES, CHANNEL_ROUTES, 4);");
  });

  it("deskmate_says tool shim re-exports the core tool", () => {
    const out = renderDeskmateSaysTool();
    expect(out).toContain('export { default } from "@deskmate/core/deskmate-says";');
  });
});

describe("renderChannelRoutes", () => {
  it("emits an empty CHANNEL_ROUTES map when the team has no channels", () => {
    const out = renderChannelRoutes(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import type { ChannelRoute } from "@deskmate/core";');
    expect(out).toContain("export const CHANNEL_ROUTES: Record<string, ChannelRoute> = {");
  });

  it("emits one entry per team.channels mapping, preserving deskmate + lock", () => {
    const team = {
      ...fixtureTeam,
      channels: {
        C0INCIDENTS: { deskmate: "devops", lock: true },
        C0GROWTH: { deskmate: "product_analyst" },
      },
    } as unknown as TeamConfig;
    const out = renderChannelRoutes(team);
    expect(out).toContain('"C0INCIDENTS": {"deskmate":"devops","lock":true}');
    expect(out).toContain('"C0GROWTH": {"deskmate":"product_analyst"}');
  });

  it("serializes the watch block deterministically", () => {
    const team = {
      ...fixtureTeam,
      channels: { C0INC: { deskmate: "devops", lock: true, watch: { react: true, reply: true, post: false, picker: "routed" } } },
    } as unknown as TeamConfig;
    const out = renderChannelRoutes(team);
    expect(out).toContain('"C0INC": {"deskmate":"devops","lock":true,"watch":{"react":true,"reply":true,"post":false,"picker":"routed"}}');
  });

  it("omits watch when the route has none", () => {
    const team = { ...fixtureTeam, channels: { C0G: { deskmate: "product_analyst" } } } as unknown as TeamConfig;
    expect(renderChannelRoutes(team)).toContain('"C0G": {"deskmate":"product_analyst"}');
  });
});

describe("renderFrontDeskInstructions", () => {
  it("prepends a generated banner to the core front-desk prose", () => {
    const out = renderFrontDeskInstructions();
    expect(out).toContain("GENERATED by");
    expect(out).toContain("# Identity");
    expect(out).toContain("# Convening multiple deskmates");
    expect(out).toContain("deskmate_says");
  });

  it("tells the front desk to keep follow-ups with the same deskmate", () => {
    const out = renderFrontDeskInstructions().toLowerCase();
    expect(out).toContain("follow-up");
    expect(out).toContain("same deskmate");
  });
});

describe("renderSubagentInstructions", () => {
  const role = "# Role: DevOps\nAuthored, verbatim.\n";

  it("keeps the authored role instructions, then appends the house style", () => {
    const out = renderSubagentInstructions(role);
    expect(out.startsWith("# Role: DevOps")).toBe(true);
    expect(out).toContain("Authored, verbatim.");
    expect(out).toContain("## How you write");
    expect(out).toContain("## Grounding and clarifying");
  });

  it("adds a voice section only when a voice line is given", () => {
    expect(renderSubagentInstructions(role)).not.toContain("## Your voice");
    const out = renderSubagentInstructions(role, "Terse SRE. Dry, not chatty.");
    expect(out).toContain("## Your voice");
    expect(out).toContain("Terse SRE. Dry, not chatty.");
  });

  it("ends with exactly one trailing newline (deterministic)", () => {
    expect(renderSubagentInstructions(role)).toMatch(/[^\n]\n$/);
  });
});

describe("renderEnvExample", () => {
  it("emits URL + TOKEN vars for each mcp connection env prefix", () => {
    const out = renderEnvExample(fixtureTeam);
    expect(out).toContain("SENTRY_MCP_URL=");
    expect(out).toContain("SENTRY_MCP_TOKEN=");
    expect(out).toContain("MIXPANEL_MCP_URL=");
    expect(out).toContain("MIXPANEL_MCP_TOKEN=");
  });

  it("skips non-mcp connections", () => {
    const out = renderEnvExample(fixtureTeam);
    expect(out).not.toContain("LEDGER_MCP_URL=");
  });

  it("does NOT seed DESKMATE_MAX_TURNS (it would override frontDesk.maxTurns)", () => {
    const out = renderEnvExample(fixtureTeam);
    expect(out).not.toContain("DESKMATE_MAX_TURNS");
  });
});

describe("renderDeskmateSweepSchedule", () => {
  it("renders a schedule that calls createDeskmateSweep with the configured cron", () => {
    const out = renderDeskmateSweepSchedule({ ...fixtureTeam, sweep: { cron: "0 8 * * 1-5" } } as any);
    expect(out).toContain('import { createDeskmateSweep } from "@deskmate/core";');
    expect(out).toContain('import { DESKMATES } from "../lib/deskmates.js";');
    expect(out).toContain('import { CHANNEL_ROUTES } from "../lib/channel-routes.js";');
    expect(out).toContain('import slack from "../channels/slack.js";');
    expect(out).toContain('createDeskmateSweep(DESKMATES, CHANNEL_ROUTES, { cron: "0 8 * * 1-5", slack })');
  });
  it("falls back to the default cron when sweep is omitted", () => {
    const out = renderDeskmateSweepSchedule(fixtureTeam);
    expect(out).toContain('"0 9 * * 1-5"');
  });
});

describe("renderStubConnection", () => {
  it("reads env vars via bracket access (valid TS even for a non-identifier prefix)", () => {
    const out = renderStubConnection("weird", "123");
    expect(out).toContain('process.env["123_MCP_URL"]');
    expect(out).toContain('process.env["123_MCP_TOKEN"]');
    // Dot access on a non-identifier prefix would be a TS/JS syntax error.
    expect(out).not.toContain("process.env.123_MCP_URL");
    expect(out).not.toContain("process.env.123_MCP_TOKEN");
  });

  it("derives the env prefix from the name when none is given, still bracketed", () => {
    const out = renderStubConnection("my_conn", undefined);
    expect(out).toContain('process.env["MY_CONN_MCP_URL"]');
    expect(out).toContain('process.env["MY_CONN_MCP_TOKEN"]');
  });
});
