import { describe, it, expect } from "vitest";
import type { TeamConfig } from "@deskmate/core";
import {
  BANNER,
  renderRootAgent,
  renderRosterRegistry,
  renderChannelRoutes,
  renderSubagentAgent,
  renderReexport,
  renderSlackChannel,
  renderSlackAmbientChannel,
  renderDeskmateSaysTool,
  renderFrontDeskInstructions,
  renderEnvExample,
} from "../src/sync/render.js";

// A minimal, hand-built TeamConfig fixture (two deskmates, two mcp connections).
// We build it as a plain object cast to TeamConfig so the renderers stay unit
// testable without importing/parsing a real config file.
const fixtureTeam = {
  model: "anthropic/claude-opus-4.6",
  frontDesk: { maxTurns: 6 },
  connections: {
    sentry: { kind: "mcp", env: "SENTRY" },
    mixpanel: { kind: "mcp", env: "MIXPANEL" },
    ledger: { kind: "tool", from: "./ledger.js" },
  },
  deskmates: {
    devops: {
      role: "devops",
      emoji: ":wrench:",
      displayName: "DevOps Engineer",
      summary: "Triages incidents.",
      reads: ["sentry"],
    },
    product_analyst: {
      role: "product_analyst",
      emoji: ":bar_chart:",
      displayName: "Product Analyst",
      summary: "Turns usage data into a narrative.",
      reads: ["mixpanel"],
    },
  },
  channels: {},
} as unknown as TeamConfig;

describe("BANNER", () => {
  it("names the command and the source of truth", () => {
    expect(BANNER).toContain("GENERATED by");
    expect(BANNER).toContain("deskmate sync");
    expect(BANNER).toContain("deskmate.config.ts");
  });
});

describe("renderRootAgent", () => {
  it("emits a defineAgent with the team model + the banner", () => {
    const out = renderRootAgent(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import { defineAgent } from "eve";');
    expect(out).toContain('model: "anthropic/claude-opus-4.6"');
    expect(out).toContain("export default defineAgent(");
  });

  it("keeps @deskmate/core external so channels don't bundle it", () => {
    const out = renderRootAgent(fixtureTeam);
    expect(out).toContain('build: { externalDependencies: ["@deskmate/core"] }');
  });
});

describe("renderSubagentAgent", () => {
  it("wires defineDeskmate(team, id) with the core + config imports", () => {
    const out = renderSubagentAgent("devops");
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import { defineDeskmate } from "@deskmate/core";');
    expect(out).toContain('import team from "../../../deskmate.config.js";');
    expect(out).toContain('export default defineDeskmate(team, "devops");');
  });
});

describe("renderRosterRegistry", () => {
  it("emits a DESKMATES Roster const with one entry per deskmate", () => {
    const out = renderRosterRegistry(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import type { Roster } from "@deskmate/core";');
    expect(out).toContain("export const DESKMATES: Roster = {");
    expect(out).toContain("devops:");
    expect(out).toContain("product_analyst:");
    expect(out).toContain('"displayName":"DevOps Engineer"');
    expect(out).toContain('"emoji":":bar_chart:"');
  });

  it("sets providers to the deskmate's reads", () => {
    const out = renderRosterRegistry(fixtureTeam);
    expect(out).toContain('"providers":["sentry"]');
    expect(out).toContain('"providers":["mixpanel"]');
  });
});

describe("renderReexport", () => {
  it("re-exports the default from the given specifier", () => {
    const out = renderReexport("../../../../roles/devops/tools/x.js");
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('export { default } from "../../../../roles/devops/tools/x.js";');
    expect(out).not.toContain("export *");
  });

  it("also re-exports named bindings when star is set", () => {
    const out = renderReexport("../x.js", { star: true });
    expect(out).toContain('export { default } from "../x.js";');
    expect(out).toContain('export * from "../x.js";');
  });
});

describe("channel + tool shims", () => {
  it("slack channel shim calls createSlackChannel(DESKMATES, CHANNEL_ROUTES)", () => {
    const out = renderSlackChannel();
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import { createSlackChannel } from "@deskmate/core/channels/slack";');
    expect(out).toContain('import { DESKMATES } from "../lib/deskmates.js";');
    expect(out).toContain('import { CHANNEL_ROUTES } from "../lib/channel-routes.js";');
    expect(out).toContain("export default createSlackChannel(DESKMATES, CHANNEL_ROUTES);");
  });

  it("slack-ambient shim calls createSlackAmbientChannel(DESKMATES, CHANNEL_ROUTES)", () => {
    const out = renderSlackAmbientChannel();
    expect(out).toContain(
      'import { createSlackAmbientChannel } from "@deskmate/core/channels/slack-ambient";',
    );
    expect(out).toContain('import { CHANNEL_ROUTES } from "../lib/channel-routes.js";');
    expect(out).toContain("export default createSlackAmbientChannel(DESKMATES, CHANNEL_ROUTES);");
  });

  it("deskmate_says tool shim re-exports the core tool", () => {
    const out = renderDeskmateSaysTool();
    expect(out).toContain('export { default } from "@deskmate/core/deskmate-says";');
  });
});

describe("renderChannelRoutes", () => {
  it("emits an empty CHANNEL_ROUTES map when the team has no channels", () => {
    const out = renderChannelRoutes(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import type { ChannelRoute } from "@deskmate/core";');
    expect(out).toContain("export const CHANNEL_ROUTES: Record<string, ChannelRoute> = {");
  });

  it("emits one entry per team.channels mapping, preserving deskmate + lock", () => {
    const team = {
      ...fixtureTeam,
      channels: {
        C0INCIDENTS: { deskmate: "devops", lock: true },
        C0GROWTH: { deskmate: "product_analyst" },
      },
    } as unknown as TeamConfig;
    const out = renderChannelRoutes(team);
    expect(out).toContain('"C0INCIDENTS": {"deskmate":"devops","lock":true}');
    expect(out).toContain('"C0GROWTH": {"deskmate":"product_analyst"}');
  });
});

describe("renderFrontDeskInstructions", () => {
  it("prepends a generated banner to the core front-desk prose", () => {
    const out = renderFrontDeskInstructions();
    expect(out).toContain("GENERATED by");
    expect(out).toContain("# Identity");
    expect(out).toContain("# Convening multiple deskmates");
    expect(out).toContain("deskmate_says");
  });
});

describe("renderEnvExample", () => {
  it("emits URL + TOKEN vars for each mcp connection env prefix", () => {
    const out = renderEnvExample(fixtureTeam);
    expect(out).toContain("SENTRY_MCP_URL=");
    expect(out).toContain("SENTRY_MCP_TOKEN=");
    expect(out).toContain("MIXPANEL_MCP_URL=");
    expect(out).toContain("MIXPANEL_MCP_TOKEN=");
  });

  it("skips non-mcp connections", () => {
    const out = renderEnvExample(fixtureTeam);
    expect(out).not.toContain("LEDGER_MCP_URL=");
  });
});
