// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
import { createMemoryReflection, resolveMemoryStore, DEFAULT_MEMORY_REFLECT_CRON } from "@deskmate/core/memory";

export default createMemoryReflection(["product_analyst"], await resolveMemoryStore(), { cron: DEFAULT_MEMORY_REFLECT_CRON });
