// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.
export { default } from "../../../../roles/product_analyst/connections/mixpanel.js";
export * from "../../../../roles/product_analyst/connections/mixpanel.js";
