export type McpTemplateOptions = {
  name: string;
  urlEnv: string;
  tokenEnv: string;
  description: string;
  tools: string[];
};

/** Pure: render the TypeScript source for a read-only, env-token MCP connection. */
export function renderMcpConnection(opts: McpTemplateOptions): string {
  const allow = opts.tools.map((t) => JSON.stringify(t)).join(", ");
  return `import { defineMcpClientConnection } from "eve/connections";

// Generated by \`pnpm deskmate:mcp:add\`. Read-only, env-token (single-deployment).
// Set ${opts.urlEnv} + ${opts.tokenEnv} to run against a real server, then redeploy.
export default defineMcpClientConnection({
  url: process.env[${JSON.stringify(opts.urlEnv)}] ?? "https://example.invalid/mcp",
  description: ${JSON.stringify(opts.description)},
  auth: { getToken: async () => ({ token: process.env[${JSON.stringify(opts.tokenEnv)}] ?? "" }) },
  tools: { allow: [${allow}] },
});
`;
}
