#!/usr/bin/env node
/**
 * Deskmate deskmate CLI.
 *
 * Activates deskmates from the library into the running agent, and keeps the
 * identity registry (agent/lib/deskmates.ts) in sync.
 *
 *   pnpm deskmate:add <id...>      copy library/deskmates/<id> -> agent/subagents/<id>
 *   pnpm deskmate:remove <id...>   delete agent/subagents/<id>
 *   pnpm deskmate:list             show the library and which deskmates are active
 *
 * Runs on Node 24+ via native TypeScript type-stripping (no build step).
 */
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import { escapeRegExp, mergeEnv } from "#scripts/env";
import { renderMcpConnection } from "#scripts/mcp-template";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const LIBRARY = join(ROOT, "library", "deskmates");
const SUBAGENTS = join(ROOT, "agent", "subagents");
const REGISTRY = join(ROOT, "agent", "lib", "deskmates.ts");

type Deskmate = {
  id: string;
  displayName: string;
  emoji: string;
  summary: string;
  skill?: string;
  providers: string[];
};

function listDir(path: string): string[] {
  if (!existsSync(path)) return [];
  return readdirSync(path, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

function readDeskmate(dir: string): Deskmate {
  return JSON.parse(readFileSync(join(dir, "deskmate.json"), "utf8")) as Deskmate;
}

function regenerateRegistry(): void {
  const active = listDir(SUBAGENTS)
    .filter((id) => existsSync(join(SUBAGENTS, id, "deskmate.json")))
    .map((id) => readDeskmate(join(SUBAGENTS, id)));

  const entries = active
    .map((e) => {
      const identity = {
        id: e.id,
        displayName: e.displayName,
        emoji: e.emoji,
        summary: e.summary,
        providers: e.providers,
      };
      return `  ${e.id}: ${JSON.stringify(identity)},`;
    })
    .join("\n");

  const body = `// AUTO-GENERATED by scripts/deskmate.ts — do not edit by hand.
// Roster of active deskmates. Change it with \`pnpm deskmate:add|remove <id>\`.
//
// Identity per deskmate, used when answering in Slack. This is also the seam that
// later becomes per-tenant / per-org config in the hosted layer.

export type DeskmateIdentity = {
  id: string;
  displayName: string;
  emoji: string;
  summary: string;
  providers: string[];
};

export const DESKMATES = {
${entries}
} as const satisfies Record<string, DeskmateIdentity>;

export type DeskmateId = keyof typeof DESKMATES;
`;

  mkdirSync(dirname(REGISTRY), { recursive: true });
  writeFileSync(REGISTRY, body);
  console.log(`✓ registry: ${active.length} active (${active.map((e) => e.id).join(", ") || "none"})`);
}

function add(ids: string[]): void {
  for (const id of ids) {
    const src = join(LIBRARY, id);
    if (!existsSync(src)) {
      console.error(`✗ ${id}: not in library/deskmates. Run \`pnpm deskmate:list\`.`);
      process.exitCode = 1;
      continue;
    }
    const dest = join(SUBAGENTS, id);
    if (existsSync(dest)) {
      console.log(`• ${id}: already active, skipping`);
      continue;
    }
    cpSync(src, dest, { recursive: true });
    const provs = readDeskmate(src).providers;
    console.log(`✓ added ${id}${provs.length ? ` (set env for: ${provs.join(", ")})` : ""}`);
  }
  regenerateRegistry();
}

function remove(ids: string[]): void {
  for (const id of ids) {
    const dest = join(SUBAGENTS, id);
    if (!existsSync(dest)) {
      console.log(`• ${id}: not active, skipping`);
      continue;
    }
    rmSync(dest, { recursive: true, force: true });
    console.log(`✓ removed ${id}`);
  }
  regenerateRegistry();
}

function list(): void {
  const active = new Set(listDir(SUBAGENTS));
  const library = listDir(LIBRARY);
  if (library.length === 0) {
    console.log("No deskmates in library/deskmates.");
    return;
  }
  console.log("Library deskmates (• = active):\n");
  for (const id of library) {
    const e = readDeskmate(join(LIBRARY, id));
    const mark = active.has(id) ? "•" : " ";
    console.log(`  ${mark} ${id.padEnd(18)} ${e.emoji} ${e.displayName} — ${e.summary}`);
  }
}

async function withPrompts<T>(
  fn: (ask: (q: string, fallback?: string) => Promise<string>) => Promise<T>,
): Promise<T> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  // Buffer lines instead of using rl.question(): piped stdin can emit every line
  // before later prompts attach a listener (dropping them), and rl.question()
  // hangs forever once stdin closes. Buffering + resolving to "" on close keeps
  // both interactive and scripted (e.g. `printf … | …`) input working, falling
  // back to each prompt's default when input runs out.
  const buffered: string[] = [];
  const waiting: Array<(line: string | null) => void> = [];
  let closed = false;
  rl.on("line", (line) => {
    const next = waiting.shift();
    if (next) next(line);
    else buffered.push(line);
  });
  rl.on("close", () => {
    closed = true;
    for (const next of waiting.splice(0)) next(null);
  });
  const nextLine = (): Promise<string | null> => {
    if (buffered.length) return Promise.resolve(buffered.shift() ?? null);
    if (closed) return Promise.resolve(null);
    return new Promise((resolve) => waiting.push(resolve));
  };
  const ask = async (q: string, fallback?: string) => {
    process.stdout.write(fallback ? `${q} [${fallback}]: ` : `${q}: `);
    const a = ((await nextLine()) ?? "").trim();
    return a || fallback || "";
  };
  try {
    return await fn(ask);
  } finally {
    rl.close();
  }
}

function appendEnvExample(keys: string[]): void {
  const path = join(ROOT, ".env.example");
  let txt = existsSync(path) ? readFileSync(path, "utf8") : "";
  for (const k of keys) {
    if (!new RegExp(`^${escapeRegExp(k)}=`, "m").test(txt)) {
      txt += `${txt.length && !txt.endsWith("\n") ? "\n" : ""}${k}=\n`;
    }
  }
  writeFileSync(path, txt);
}

async function mcpAdd(args: string[]): Promise<void> {
  const name = args[0];
  const toIdx = args.indexOf("--to");
  const deskmate = toIdx >= 0 ? args[toIdx + 1] : undefined;
  if (!name || !deskmate) throw new Error("usage: pnpm deskmate:mcp:add <name> --to <deskmate>");
  if (!/^[a-z][a-z0-9_]*$/.test(name)) {
    throw new Error("<name> must be a snake_case identifier (lowercase letter, then letters/digits/underscores).");
  }
  const dest = join(SUBAGENTS, deskmate);
  if (!existsSync(dest)) {
    throw new Error(`${deskmate} is not active. Run \`pnpm deskmate:add ${deskmate}\` first.`);
  }
  const upper = name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
  await withPrompts(async (ask) => {
    const urlEnv = await ask("URL env var", `${upper}_MCP_URL`);
    const tokenEnv = await ask("Token env var", `${upper}_MCP_TOKEN`);
    const description = await ask("Description (for the model)", `Read-only ${name} MCP.`);
    const toolsRaw = await ask("Read tools (comma-separated)", "");
    const tools = toolsRaw.split(",").map((t) => t.trim()).filter(Boolean);
    const file = join(dest, "connections", `${name}.ts`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, renderMcpConnection({ name, urlEnv, tokenEnv, description, tools }));
    appendEnvExample([urlEnv, tokenEnv]);
    console.log(`✓ created ${file}`);
    console.log(`  set ${urlEnv} + ${tokenEnv} in your env, then redeploy.`);
  });
}

async function init(): Promise<void> {
  const library = listDir(LIBRARY);
  if (library.length === 0) throw new Error("No deskmates in library/deskmates.");
  console.log("Library deskmates:");
  library.forEach((id, i) => console.log(`  ${i + 1}. ${id}`));
  await withPrompts(async (ask) => {
    const raw = await ask("Activate which? (comma-separated names or numbers)", "");
    const ids = raw
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
      .map((p) => (/^\d+$/.test(p) ? library[Number(p) - 1] : p))
      .filter((id): id is string => Boolean(id) && library.includes(id));
    if (ids.length === 0) {
      console.log("Nothing selected.");
      return;
    }
    add(ids);
    const updates: Record<string, string> = {};
    for (const id of ids) {
      for (const prov of readDeskmate(join(LIBRARY, id)).providers) {
        const up = prov.toUpperCase().replace(/[^A-Z0-9]/g, "_");
        const url = await ask(`${id}: ${prov} MCP URL`, "");
        const token = await ask(`${id}: ${prov} MCP token`, "");
        if (url) updates[`${up}_MCP_URL`] = url;
        if (token) updates[`${up}_MCP_TOKEN`] = token;
      }
    }
    if (Object.keys(updates).length) {
      const envPath = join(ROOT, ".env");
      const existing = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
      writeFileSync(envPath, mergeEnv(existing, updates));
      console.log("\n✓ activated + wrote .env.");
    } else {
      console.log("\n✓ activated.");
    }
    console.log("Next: set up Slack (see README → Finish setup), then `vercel deploy`.");
  });
}

const [command, ...ids] = process.argv.slice(2);
switch (command) {
  case "add":
    if (ids.length === 0) throw new Error("usage: pnpm deskmate:add <id...>");
    add(ids);
    break;
  case "remove":
    if (ids.length === 0) throw new Error("usage: pnpm deskmate:remove <id...>");
    remove(ids);
    break;
  case "list":
    list();
    break;
  case "mcp-add":
    await mcpAdd(ids);
    break;
  case "init":
    await init();
    break;
  default:
    console.log(
      "usage: pnpm deskmate:(add|remove|list|init) [id...]\n" +
        "       pnpm deskmate:mcp:add <name> --to <deskmate>",
    );
    process.exitCode = command ? 1 : 0;
}
