#!/usr/bin/env node
/**
 * Deskmate deskmate CLI.
 *
 * Activates deskmates from the library into the running agent, and keeps the
 * identity registry (agent/lib/deskmates.ts) in sync.
 *
 *   pnpm deskmate:add <id...>      copy library/deskmates/<id> -> agent/subagents/<id>
 *   pnpm deskmate:remove <id...>   delete agent/subagents/<id>
 *   pnpm deskmate:list             show the library and which deskmates are active
 *
 * Runs on Node 24+ via native TypeScript type-stripping (no build step).
 */
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const LIBRARY = join(ROOT, "library", "deskmates");
const SUBAGENTS = join(ROOT, "agent", "subagents");
const REGISTRY = join(ROOT, "agent", "lib", "deskmates.ts");

type Deskmate = {
  id: string;
  displayName: string;
  emoji: string;
  summary: string;
  skill?: string;
  providers: string[];
};

function listDir(path: string): string[] {
  if (!existsSync(path)) return [];
  return readdirSync(path, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

function readDeskmate(dir: string): Deskmate {
  return JSON.parse(readFileSync(join(dir, "deskmate.json"), "utf8")) as Deskmate;
}

function regenerateRegistry(): void {
  const active = listDir(SUBAGENTS)
    .filter((id) => existsSync(join(SUBAGENTS, id, "deskmate.json")))
    .map((id) => readDeskmate(join(SUBAGENTS, id)));

  const entries = active
    .map((e) => {
      const identity = {
        id: e.id,
        displayName: e.displayName,
        emoji: e.emoji,
        summary: e.summary,
        providers: e.providers,
      };
      return `  ${e.id}: ${JSON.stringify(identity)},`;
    })
    .join("\n");

  const body = `// AUTO-GENERATED by scripts/deskmate.ts — do not edit by hand.
// Roster of active deskmates. Change it with \`pnpm deskmate:add|remove <id>\`.
//
// Identity per deskmate, used when answering in Slack. This is also the seam that
// later becomes per-tenant / per-org config in the hosted layer.

export type DeskmateIdentity = {
  id: string;
  displayName: string;
  emoji: string;
  summary: string;
  providers: string[];
};

export const DESKMATES = {
${entries}
} as const satisfies Record<string, DeskmateIdentity>;

export type DeskmateId = keyof typeof DESKMATES;
`;

  mkdirSync(dirname(REGISTRY), { recursive: true });
  writeFileSync(REGISTRY, body);
  console.log(`✓ registry: ${active.length} active (${active.map((e) => e.id).join(", ") || "none"})`);
}

function add(ids: string[]): void {
  for (const id of ids) {
    const src = join(LIBRARY, id);
    if (!existsSync(src)) {
      console.error(`✗ ${id}: not in library/deskmates. Run \`pnpm deskmate:list\`.`);
      process.exitCode = 1;
      continue;
    }
    const dest = join(SUBAGENTS, id);
    if (existsSync(dest)) {
      console.log(`• ${id}: already active, skipping`);
      continue;
    }
    cpSync(src, dest, { recursive: true });
    const provs = readDeskmate(src).providers;
    console.log(`✓ added ${id}${provs.length ? ` (set env for: ${provs.join(", ")})` : ""}`);
  }
  regenerateRegistry();
}

function remove(ids: string[]): void {
  for (const id of ids) {
    const dest = join(SUBAGENTS, id);
    if (!existsSync(dest)) {
      console.log(`• ${id}: not active, skipping`);
      continue;
    }
    rmSync(dest, { recursive: true, force: true });
    console.log(`✓ removed ${id}`);
  }
  regenerateRegistry();
}

function list(): void {
  const active = new Set(listDir(SUBAGENTS));
  const library = listDir(LIBRARY);
  if (library.length === 0) {
    console.log("No deskmates in library/deskmates.");
    return;
  }
  console.log("Library deskmates (• = active):\n");
  for (const id of library) {
    const e = readDeskmate(join(LIBRARY, id));
    const mark = active.has(id) ? "•" : " ";
    console.log(`  ${mark} ${id.padEnd(18)} ${e.emoji} ${e.displayName} — ${e.summary}`);
  }
}

const [command, ...ids] = process.argv.slice(2);
switch (command) {
  case "add":
    if (ids.length === 0) throw new Error("usage: pnpm deskmate:add <id...>");
    add(ids);
    break;
  case "remove":
    if (ids.length === 0) throw new Error("usage: pnpm deskmate:remove <id...>");
    remove(ids);
    break;
  case "list":
    list();
    break;
  default:
    console.log("usage: pnpm deskmate:(add|remove|list) [id...]");
    process.exitCode = command ? 1 : 0;
}
