import { createRequire } from "node:module";
import type { ChannelRoute, TeamConfig } from "@deskmate/core";
import { DEFAULT_SWEEP_CRON } from "@deskmate/core";

// Lazy accessor for core's front-desk prose. Importing it at module top-level made
// EVERY CLI command read core's `.md` at startup (this module is on the shared
// import graph); reading it only when `renderFrontDeskInstructions()` runs keeps
// `deskmate list`/`add`/etc. cheap. A synchronous `require` (of core's ESM export)
// keeps the renderers sync so `planSync` stays sync.
const require = createRequire(import.meta.url);

// Pure renderers for `deskmate sync`. Each returns the full text of one generated
// file, prefixed with the GENERATED banner so the consumer knows not to hand-edit
// it. No filesystem access here — these are string transforms over a TeamConfig,
// which keeps them trivially unit-testable (see test/render.test.ts).

/** The banner every generated CODE file starts with (see below for the .md/.env variants). */
export const BANNER = "// GENERATED by `deskmate sync` — edit deskmate.config.ts instead.";

/** `agent/agent.ts` — the front-desk root agent, running the team's default model. */
export function renderRootAgent(team: TeamConfig): string {
  return `${BANNER}
import { defineAgent } from "eve";

export default defineAgent({
  model: ${JSON.stringify(team.model)},
  // Keep @deskmate/core external so Eve traces it in the hosted output instead of
  // bundling it into each authored channel. Bundling it pulls core's transitive
  // deps (@vercel/connect, ai) into rolldown's per-channel graph and breaks the
  // build; a normally-installed core in node_modules is externalized anyway.
  build: { externalDependencies: ["@deskmate/core"] },
});
`;
}

/**
 * `agent/lib/deskmates.ts` — the roster registry core's channels consume. One
 * `DESKMATES` entry per deskmate, typed as core's `Roster`, with `providers` set
 * to the deskmate's `reads`. Values are JSON-encoded so any quoting/escaping in the
 * display strings stays correct.
 */
export function renderRosterRegistry(team: TeamConfig): string {
  const entries = Object.entries(team.deskmates).map(([id, d]) => {
    const identity = {
      id,
      displayName: d.displayName,
      emoji: d.emoji,
      summary: d.summary,
      providers: d.reads,
    };
    return `  ${id}: ${JSON.stringify(identity)},`;
  });
  return `${BANNER}
import type { Roster } from "@deskmate/core";

export const DESKMATES: Roster = {
${entries.join("\n")}
};
`;
}

/**
 * `agent/lib/channel-routes.ts` — the Slack channel→deskmate routing table core's
 * channels consume. One entry per `team.channels` mapping, typed as core's
 * `ChannelRoute`. Values are JSON-encoded so any quoting stays correct. Without this
 * file the routes in `deskmate.config.ts` would be validated but never applied.
 */
export function renderChannelRoutes(team: TeamConfig): string {
  const entries = Object.entries(team.channels).map(([channel, route]) => {
    const value: ChannelRoute = { deskmate: route.deskmate };
    if (route.lock !== undefined) value.lock = route.lock;
    if (route.watch !== undefined) value.watch = route.watch;
    return `  ${JSON.stringify(channel)}: ${JSON.stringify(value)},`;
  });
  return `${BANNER}
import type { ChannelRoute } from "@deskmate/core";

export const CHANNEL_ROUTES: Record<string, ChannelRoute> = {
${entries.join("\n")}
};
`;
}

/**
 * `agent/subagents/<id>/agent.ts` — a deskmate subagent shim. It re-derives the
 * agent config from the repo-root `deskmate.config.ts` (three levels up from
 * `agent/subagents/<id>/`) so the deskmate's description/model always tracks config.
 */
export function renderSubagentAgent(id: string): string {
  return `${BANNER}
import { defineDeskmate } from "@deskmate/core";
import team from "../../../deskmate.config.js";

export default defineDeskmate(team, ${JSON.stringify(id)});
`;
}

/**
 * Generic re-export shim. Re-exports the default export from `relImportPath`
 * (an eve tool/connection/channel authored elsewhere); with `{ star: true }` it
 * also re-exports the module's named bindings.
 */
export function renderReexport(relImportPath: string, opts?: { star?: boolean }): string {
  const lines = [BANNER, `export { default } from ${JSON.stringify(relImportPath)};`];
  if (opts?.star) lines.push(`export * from ${JSON.stringify(relImportPath)};`);
  return `${lines.join("\n")}\n`;
}

/**
 * `agent/channels/slack.ts` — build the managed Slack channel from the roster +
 * routes. The consumer's `team.frontDesk.maxTurns` is baked in as the convene cap
 * (env `DESKMATE_MAX_TURNS` still overrides it at runtime).
 */
export function renderSlackChannel(team: TeamConfig): string {
  return `${BANNER}
import { createSlackChannel } from "@deskmate/core/channels/slack";
import { DESKMATES } from "../lib/deskmates.js";
import { CHANNEL_ROUTES } from "../lib/channel-routes.js";

export default createSlackChannel(DESKMATES, CHANNEL_ROUTES, ${team.frontDesk.maxTurns});
`;
}

/** `agent/channels/slack-ambient.ts` — the ambient (no-mention) Slack channel. */
export function renderSlackAmbientChannel(team: TeamConfig): string {
  return `${BANNER}
import { createSlackAmbientChannel } from "@deskmate/core/channels/slack-ambient";
import { DESKMATES } from "../lib/deskmates.js";
import { CHANNEL_ROUTES } from "../lib/channel-routes.js";

export default createSlackAmbientChannel(DESKMATES, CHANNEL_ROUTES, ${team.frontDesk.maxTurns});
`;
}

/** `agent/channels/eve.ts` — re-export core's default eve channel. */
export function renderEveChannel(): string {
  return renderReexport("@deskmate/core/channels/eve");
}

/** `agent/channels/deskmate-avatars.ts` — re-export core's avatar channel. */
export function renderAvatarsChannel(): string {
  return renderReexport("@deskmate/core/channels/deskmate-avatars");
}

/** `agent/tools/deskmate_says.ts` — re-export core's front-desk `deskmate_says` tool. */
export function renderDeskmateSaysTool(): string {
  return renderReexport("@deskmate/core/deskmate-says");
}

/**
 * `agent/instructions.md` — the front-desk router prose, from core's template.
 * Markdown gets an HTML-comment banner (a `//` line would render as body text).
 * NOTE: subagent instructions are NOT this — they're composed (no banner) by
 * `renderSubagentInstructions` from the role file + core's house style. See plan.ts.
 */
export function renderFrontDeskInstructions(): string {
  const { frontDeskInstructions } = require("@deskmate/core/front-desk-instructions") as {
    frontDeskInstructions: string;
  };
  return `<!-- GENERATED by \`deskmate sync\` — edit deskmate.config.ts instead. -->\n\n${frontDeskInstructions}`;
}

/**
 * `agent/subagents/<id>/instructions.md` — the authored role instructions composed
 * with core's shared house-style block (voice + work discipline) and, when set, the
 * deskmate's one-line `voice`. Authoring the house style once in core (instead of
 * copy-pasting it into every role file) is why this composes at sync time rather than
 * copying the role file verbatim. Role prose comes first (who you are / how this role
 * works), then the shared style, then the per-deskmate voice. Exactly one trailing
 * newline keeps the write deterministic → idempotent. Lazy `require` (same as the
 * front-desk prose) so unrelated CLI commands don't read core's `.md` at startup.
 */
export function renderSubagentInstructions(roleInstructions: string, voice?: string): string {
  const { houseStyle } = require("@deskmate/core/house-style") as { houseStyle: string };
  const voiceBlock = voice ? `\n\n## Your voice\n${voice}` : "";
  return `${roleInstructions.trimEnd()}\n\n${houseStyle.trimEnd()}${voiceBlock}\n`;
}

/**
 * `agent/schedules/deskmate-sweep.ts` — the Phase-2 scheduled sweep. Emitted only
 * when a channel opts into `watch.digest` (see plan.ts). One team-level cron.
 */
export function renderDeskmateSweepSchedule(team: TeamConfig): string {
  const cron = team.sweep?.cron ?? DEFAULT_SWEEP_CRON;
  return `${BANNER}
import { createDeskmateSweep } from "@deskmate/core";
import { DESKMATES } from "../lib/deskmates.js";
import { CHANNEL_ROUTES } from "../lib/channel-routes.js";
import slack from "../channels/slack.js";

export default createDeskmateSweep(DESKMATES, CHANNEL_ROUTES, { cron: ${JSON.stringify(cron)}, slack });
`;
}

/** The three long-term-memory tools generated (one file each) for a memory-enabled deskmate. */
export type MemoryToolName = "remember" | "recall" | "forget";

/**
 * `agent/subagents/<id>/tools/<remember|recall|forget>.ts` — one memory tool shim.
 * Re-exports a single tool off core's `createMemoryTools(id)` factory, bound to this
 * deskmate's id (which scopes its memory). All logic lives in `@deskmate/core/memory`.
 */
export function renderMemoryTool(id: string, tool: MemoryToolName): string {
  return `${BANNER}
import { createMemoryTools } from "@deskmate/core/memory";

export default createMemoryTools(${JSON.stringify(id)}).${tool};
`;
}

/**
 * `agent/subagents/<id>/instructions/memory.ts` — the per-turn dynamic-recall entry
 * that pins this deskmate's core memory into context. It is a directory entry that
 * COEXISTS with the composed root `agent/subagents/<id>/instructions.md` (eve reads
 * `instructions/*` alongside `instructions.md`; the root file comes first, then the
 * sorted directory entries). `coreLimit` is the deskmate's `memory.coreLimit`,
 * JSON-encoded as a number.
 */
export function renderMemoryInstructions(id: string, coreLimit: number): string {
  return `${BANNER}
import { createMemoryInstructions } from "@deskmate/core/memory";

export default createMemoryInstructions(${JSON.stringify(id)}, ${JSON.stringify(coreLimit)});
`;
}

/**
 * `agent/schedules/memory-reflection.ts` — the deployment-root nightly reflection
 * ("dreaming") schedule. Schedules are root-only, so this lives at the agent root,
 * NOT under any subagent. Emitted exactly once, only when ≥1 deskmate opts into
 * memory (see plan.ts). `deskmateIds` is the JSON array of memory-enabled ids.
 *
 * `cron`: the team's `memory.reflect.cron` when set (emitted as a JSON string), else
 * the imported `DEFAULT_MEMORY_REFLECT_CRON` identifier (so the generated file tracks
 * core's canonical default). We only import the default when it is actually used, to
 * avoid an unused import in the override case.
 *
 * Store wiring uses top-level `await resolveMemoryStore()`: core's
 * `createMemoryReflection` takes a RESOLVED `MemoryStore`, so the store must be
 * awaited before the schedule is constructed. That is valid ESM; its acceptance under
 * `eve build` is validated in a later task.
 */
export function renderMemoryReflectionSchedule(deskmateIds: string[], cron?: string): string {
  const overridden = cron !== undefined;
  const named = overridden
    ? "createMemoryReflection, resolveMemoryStore"
    : "createMemoryReflection, resolveMemoryStore, DEFAULT_MEMORY_REFLECT_CRON";
  const cronArg = overridden ? JSON.stringify(cron) : "DEFAULT_MEMORY_REFLECT_CRON";
  return `${BANNER}
import { ${named} } from "@deskmate/core/memory";

export default createMemoryReflection(${JSON.stringify(deskmateIds)}, await resolveMemoryStore(), { cron: ${cronArg} });
`;
}

/**
 * A TODO-stub connection, emitted when a deskmate `reads` a connection but no
 * authored file (`roles/<id>/connections/<name>.ts` or shared `connections/<name>.ts`)
 * exists. It is a valid eve connection so `eve build` doesn't crash on a dangling
 * import; the banner + TODO make the gap obvious.
 */
export function renderStubConnection(name: string, envPrefix: string | undefined): string {
  const prefix = envPrefix ?? name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
  return `${BANNER}
// TODO(deskmate sync): no authored connection file found for "${name}". Expected one of:
//   roles/<id>/connections/${name}.ts   (deskmate-local)
//   connections/${name}.ts              (shared, at the repo root)
// Scaffold one with \`deskmate mcp-add ${name}\`, then re-run \`deskmate sync\`.
import { defineMcpClientConnection } from "eve/connections";

export default defineMcpClientConnection({
  url: process.env[${JSON.stringify(`${prefix}_MCP_URL`)}] ?? "https://example.invalid/mcp",
  description: "TODO: replace this stub — the authored connection for \\"${name}\\" is missing.",
  auth: { getToken: async () => ({ token: process.env[${JSON.stringify(`${prefix}_MCP_TOKEN`)}] ?? "" }) },
  tools: { allow: [] },
});
`;
}

/**
 * `.env.example` — a static preamble (model access, Slack) plus one URL/TOKEN pair
 * per `{ kind: "mcp", env }` connection in the config. Non-mcp connections and mcp
 * connections without an `env` prefix are skipped.
 *
 * Deliberately does NOT seed `DESKMATE_MAX_TURNS`: `maxTurns()` treats that env var
 * as a RUNTIME OVERRIDE of `frontDesk.maxTurns`, so listing it here would mean copying
 * this file into the deploy env silently reverts a custom config cap. The turn cap
 * lives in `frontDesk.maxTurns`; the env var stays an optional ops-only override.
 */
export function renderEnvExample(team: TeamConfig): string {
  const preamble = `# GENERATED by \`deskmate sync\` — edit deskmate.config.ts instead.

# ── Model access (pick one) ───────────────────────────────────────────────
# Models resolve through the Vercel AI Gateway. Either set a gateway key:
AI_GATEWAY_API_KEY=
# …or run \`vercel link\` + \`vercel env pull\` to get VERCEL_OIDC_TOKEN automatically.

# ── Slack (Vercel Connect) ────────────────────────────────────────────────
# The Connect connector UID you provision for Slack (see README → Slack setup).
SLACK_CONNECTOR=slack/deskmate

# ── Deskmate MCP connections (single-deployment, env-token model) ──────────
# Set the URL + token for the connections your deskmates read; leave the rest
# blank. With no URL a connection falls back to a placeholder and returns no
# tools at call time.`;

  const blocks = Object.entries(team.connections)
    .filter(([, c]) => c.kind === "mcp" && !!c.env)
    .map(([name, c]) => `# ${name}\n${c.env}_MCP_URL=\n${c.env}_MCP_TOKEN=`);

  const body = blocks.length ? `\n\n${blocks.join("\n\n")}` : "";
  return `${preamble}${body}\n`;
}
